name: Deploy React App

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch (adjust if needed)

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Set the appropriate Node.js version for your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React app
      - name: Build React app
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to the gh-pages branch
          folder: dist  # The folder that contains the production-ready build
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
